/*
* generated by Xtext
*/
package ptlide.xtext.ui.outline;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.ui.PluginImageHelper;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import com.google.inject.Inject;

import ptlide.xtext.ptl.Description;
import ptlide.xtext.ptl.Goal;
import ptlide.xtext.ptl.Goals;
import ptlide.xtext.ptl.Participant;
import ptlide.xtext.ptl.Participants;
import ptlide.xtext.ptl.Protocol;
import ptlide.xtext.ptl.State;
import ptlide.xtext.ptl.States;
import ptlide.xtext.ptl.Transition;
import ptlide.xtext.ptl.Transitions;

/**
 * customization of the default outline structure
 * 
 */
public class PtlOutlineTreeProvider extends DefaultOutlineTreeProvider {
	@Inject private PluginImageHelper imageHelper;
	
	public PtlOutlineTreeProvider() {
		super();
	}
	
	@Override
	protected boolean _isLeaf(EObject node) {
		return (node instanceof State || node instanceof Transition || node instanceof Participant || node instanceof Goal || node instanceof Description);
	}
	
	@Override
	protected Image _image(Object element) {
		if (element instanceof Participant && ((Participant) element).getParticipantDescription() != null && ((Participant) element).getParticipantDescription().getKind() != null) {
			if (((Participant) element).getParticipantDescription().getKind().equals("agent")) {
				return imageHelper.getImage("agent.gif");
			}
			return imageHelper.getImage("artifact.gif");
		} else if (element instanceof State && ((State) element).getType() != null) {
			if (((State) element).getType().getInitial() != null) {
				return imageHelper.getImage("initial.gif"); 
			} else if (((State) element).getType().getFinal() != null) {
				return imageHelper.getImage("final.gif");
			} else {
				return imageHelper.getImage("normal.gif");
			}
		} else if (element instanceof Goal) {
			return imageHelper.getImage("goal.gif");
		} else if (element instanceof Transition) {
			return imageHelper.getImage("transition.gif");
		} else if (element instanceof Protocol) {
			return imageHelper.getImage("protocol.gif");
		} else if (element instanceof Description) {
			return imageHelper.getImage("description.gif");
		} else if (element instanceof Transitions || element instanceof States || element instanceof Goals || element instanceof Participants) {
			return imageHelper.getImage("others.gif");
		}
		return super._image(element);
	}
}
