/* Generated By:JavaCC: Do not edit this line. PtlParserConstants.java */
package ptlparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PtlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TK_PROTOCOL = 7;
  /** RegularExpression Id. */
  int TK_DESCRIPTION = 8;
  /** RegularExpression Id. */
  int TK_GOALS = 9;
  /** RegularExpression Id. */
  int TK_PARTICIPANTS = 10;
  /** RegularExpression Id. */
  int TK_AGENT = 11;
  /** RegularExpression Id. */
  int TK_ARTIFACT = 12;
  /** RegularExpression Id. */
  int TK_MAX = 13;
  /** RegularExpression Id. */
  int TK_MIN = 14;
  /** RegularExpression Id. */
  int TK_STATES = 15;
  /** RegularExpression Id. */
  int TK_INITIAL = 16;
  /** RegularExpression Id. */
  int TK_FINAL = 17;
  /** RegularExpression Id. */
  int TK_TRANSITIONS = 18;
  /** RegularExpression Id. */
  int TK_TIMEOUT = 19;
  /** RegularExpression Id. */
  int TK_MESSAGE = 20;
  /** RegularExpression Id. */
  int TK_ACTION = 21;
  /** RegularExpression Id. */
  int TK_EVENT = 22;
  /** RegularExpression Id. */
  int TK_TRIGGER = 23;
  /** RegularExpression Id. */
  int TK_IMPORT = 24;
  /** RegularExpression Id. */
  int TK_MAPPING = 25;
  /** RegularExpression Id. */
  int TK_ALL = 26;
  /** RegularExpression Id. */
  int TK_PLUS = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;
  /** RegularExpression Id. */
  int STRING = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int LETTER = 31;
  /** RegularExpression Id. */
  int LC_LETTER = 32;
  /** RegularExpression Id. */
  int UP_LETTER = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"protocol\"",
    "\"description\"",
    "\"goals\"",
    "\"participants\"",
    "\"agent\"",
    "\"artifact\"",
    "\"max\"",
    "\"min\"",
    "\"states\"",
    "\"initial\"",
    "\"final\"",
    "\"transitions\"",
    "\"timeout\"",
    "\"message\"",
    "\"action\"",
    "\"event\"",
    "\"trigger\"",
    "\"import\"",
    "\"mapping\"",
    "\"all\"",
    "\"+\"",
    "<INTEGER>",
    "<STRING>",
    "<ID>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"-\"",
    "\"#\"",
    "\";\"",
    "\"--\"",
    "\"->\"",
    "\"[\"",
    "\"]\"",
  };

}
