/*
 * generated by Xtext
 */
package ptlide.xtext;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

import ptlide.xtext.scoping.PtlDeclarativeQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PtlRuntimeModule extends ptlide.xtext.AbstractPtlRuntimeModule {
    @Override
    public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return PtlDeclarativeQualifiedNameProvider.class;
    }
}
