/*
* generated by Xtext
*/
package ptlide.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ptlide.xtext.services.PtlGrammarAccess;

public class PtlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PtlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT", "RULE_ML_COMMENT");
	}
	
	@Override
	protected ptlide.xtext.parser.antlr.internal.InternalPtlParser createParser(XtextTokenStream stream) {
		return new ptlide.xtext.parser.antlr.internal.InternalPtlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Protocol";
	}
	
	public PtlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PtlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
