/*
 * generated by Xtext
 */
package ptlide.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ptlide.xtext.ui.internal.PtlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PtlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PtlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PtlActivator.getInstance().getInjector(PtlActivator.PTLIDE_XTEXT_PTL);
	}
	
}
