/*
 * generated by Xtext
 */
package ptlide.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import com.google.inject.Binder;

import ptlide.xtext.ui.outline.PtlOutlineTreeProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PtlUiModule extends ptlide.xtext.ui.AbstractPtlUiModule {
	public PtlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	    return PtlHighlightingConfiguration.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		return PtlHighlightingCalculator.class;
	}
	
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
	    return PtlOutlineTreeProvider.class;
	}
}
